[supervisord]
user=root
nodaemon=true

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work rabbitmq --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
startretries=10
startsecs=5
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/worker.log

[program:employee-consumer]
command=php /var/www/html/artisan rabbitmq:consume-employees
autostart=true
autorestart=true
startretries=10
startsecs=5
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/employee-consumer.log
