name: luminarh-platform

networks:
  luminarh_net:
    driver: bridge

volumes:
  postgres_data:
#  redis_data:

services:

  # ─── DATABASE ─────────────────────────────────────────────
  luminarh-db:
    image: postgres:15-alpine
    container_name: luminarh-db
    restart: unless-stopped
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: luminarh_db
      POSTGRES_USER: luminarh_user
      POSTGRES_PASSWORD: luminarh_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - luminarh_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U luminarh_user -d luminarh_db"]
      interval: 10s
      timeout: 5s
      retries: 5

#  # ─── REDIS ────────────────────────────────────────────────
#  redis:
#    image: redis:7-alpine
#    container_name: redis
#    restart: unless-stopped
#    volumes:
#      - redis_data:/data
#    networks:
#      - luminarh_net
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  # ─── KEYCLOAK (IAM) ───────────────────────────────────────
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    command: start-dev --import-realm
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    volumes:
      - ./keycloak/luminarh-realm.json:/opt/keycloak/data/import/luminarh-realm.json:ro
    networks:
      - luminarh_net

  # ─── LUMINA RH MONOLITH ──────────────────────────────────
  luminarh-service:
    build:
      context: ./services/luminaRh
      dockerfile: Dockerfile
    container_name: luminarh-service
    command: npm run start
    restart: unless-stopped
    ports:
      - "8001:3000"   # Expose directement sur le port 8001 (remplace Kong)
    volumes:
      - ./services/luminaRh:/app
      - /app/node_modules
    env_file:
      - ./services/luminaRh/.env
    environment:
      - DATABASE_URL=postgresql://luminarh_user:luminarh_pass@luminarh-db:5432/luminarh_db?schema=public
#      - REDIS_HOST=redis
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=luminarh
      - KEYCLOAK_CLIENT_ID=luminarh-backend
      - KEYCLOAK_CLIENT_SECRET=z9yDCh9WO3B8PclSsZirS5nXLZWmCRVU
      - PORT=3000
    depends_on:
      luminarh-db:
        condition: service_healthy
#      redis:
#        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - luminarh_net

#  # ─── FRONTEND ────────────────────────────────────────────
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#      args:
#        VITE_API_URL: ""
#    container_name: frontend
#    restart: unless-stopped
#    ports:
#      - "3000:80"
#    depends_on:
#      - luminarh-service
#    networks:
#      - luminarh_net
