[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
 
[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
 
[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
 
[program:rabbitmq-analytics]
command=php /var/www/html/artisan rabbitmq:consume-analytics
autostart=true
autorestart=true
startsecs=5
startretries=10
stderr_logfile=/var/log/rabbitmq-analytics.err.log
stdout_logfile=/var/log/rabbitmq-analytics.out.log

[program:rabbitmq-employees]
command=php /var/www/html/artisan rabbitmq:consume-employees
autostart=true
autorestart=true
startsecs=5
startretries=10
stderr_logfile=/var/log/rabbitmq-employees.err.log
stdout_logfile=/var/log/rabbitmq-employees.out.log
